title: "Anorm"
description: "The simple SQL data access"
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

exclude: [README.md, jekyll.sh, anorm]
baseUrl: "/anorm"
latest_major_release: 2.5
latest_release: 2.5.3

_2_5_latest_minor: 2.5.3
